# scripts to run before build
before_build:
  - nuget restore
build:
  parallel: true                  # enable MSBuild parallel builds
  project: WeatherAPIDemo.sln     # path to Visual Studio solution or project
  publish_wap: true
